name: doodle_drops
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
